// SPDX-FileCopyrightText: 2025 NOI Techpark <digital@noi.bz.it>
//
// SPDX-License-Identifier: AGPL-3.0-or-later
/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { ViewLayout } from "./data/breakpoints";
import { AirQualityShort } from "./data/air-quality/AirQualityShort";
import { IconName } from "./blocks/icon/icon.component";
import { Map } from "leaflet";
export { ViewLayout } from "./data/breakpoints";
export { AirQualityShort } from "./data/air-quality/AirQualityShort";
export { IconName } from "./blocks/icon/icon.component";
export { Map } from "leaflet";
export namespace Components {
    /**
     * Road air quality component
     */
    interface NoiA22AirQuality {
        /**
          * Language
         */
        "language": string;
        /**
          * Layout appearance
         */
        "layout": ViewLayout;
        /**
          * Reload camera data
         */
        "refreshData": () => Promise<void>;
    }
    /**
     * (INTERNAL) part of 'noi-a22-air-quality'
     */
    interface NoiAirQualityList {
        "idSelected": string;
        "layout": ViewLayout;
        "stationArr": AirQualityShort[] | null;
    }
    /**
     * (INTERNAL) Backdrop component.
     */
    interface NoiBackdrop {
        /**
          * Removing backdrop from DOM sometime can cause blink during layout recalculation. 'hidden' can be used to hide the backdrop without removing from DOM
          * @default false
         */
        "hidden": boolean;
    }
    /**
     * (INTERNAL) Backdrop component.
     */
    interface NoiButton {
        /**
          * button 'disabled' property
          * @default false
         */
        "disabled": boolean;
        /**
          * icon-only buttons has circle shape. The size of the button can be changed with "font-size" style
          * @default false
         */
        "iconOnly": boolean;
    }
    /**
     * (INTERNAL) render an icon.
     * Icons are embedded inside the component (so far).
     * Icon size can be changed by 'font-size' style
     */
    interface NoiIcon {
        /**
          * icon name
         */
        "name": IconName | string;
    }
    /**
     * (INTERNAL) render an input with prefix and clear button
     * Prefix are hardcoded to 'search' icon for now.
     */
    interface NoiInput {
        /**
          * Input placeholder
         */
        "placeholder": string;
    }
    /**
     * (INTERNAL) render leaflet map
     */
    interface NoiMap {
    }
}
export interface NoiAirQualityListCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLNoiAirQualityListElement;
}
export interface NoiBackdropCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLNoiBackdropElement;
}
export interface NoiButtonCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLNoiButtonElement;
}
export interface NoiInputCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLNoiInputElement;
}
export interface NoiMapCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLNoiMapElement;
}
declare global {
    /**
     * Road air quality component
     */
    interface HTMLNoiA22AirQualityElement extends Components.NoiA22AirQuality, HTMLStencilElement {
    }
    var HTMLNoiA22AirQualityElement: {
        prototype: HTMLNoiA22AirQualityElement;
        new (): HTMLNoiA22AirQualityElement;
    };
    interface HTMLNoiAirQualityListElementEventMap {
        "itemClick": AirQualityShort;
    }
    /**
     * (INTERNAL) part of 'noi-a22-air-quality'
     */
    interface HTMLNoiAirQualityListElement extends Components.NoiAirQualityList, HTMLStencilElement {
        addEventListener<K extends keyof HTMLNoiAirQualityListElementEventMap>(type: K, listener: (this: HTMLNoiAirQualityListElement, ev: NoiAirQualityListCustomEvent<HTMLNoiAirQualityListElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLNoiAirQualityListElementEventMap>(type: K, listener: (this: HTMLNoiAirQualityListElement, ev: NoiAirQualityListCustomEvent<HTMLNoiAirQualityListElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLNoiAirQualityListElement: {
        prototype: HTMLNoiAirQualityListElement;
        new (): HTMLNoiAirQualityListElement;
    };
    interface HTMLNoiBackdropElementEventMap {
        "backdropClick": void;
    }
    /**
     * (INTERNAL) Backdrop component.
     */
    interface HTMLNoiBackdropElement extends Components.NoiBackdrop, HTMLStencilElement {
        addEventListener<K extends keyof HTMLNoiBackdropElementEventMap>(type: K, listener: (this: HTMLNoiBackdropElement, ev: NoiBackdropCustomEvent<HTMLNoiBackdropElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLNoiBackdropElementEventMap>(type: K, listener: (this: HTMLNoiBackdropElement, ev: NoiBackdropCustomEvent<HTMLNoiBackdropElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLNoiBackdropElement: {
        prototype: HTMLNoiBackdropElement;
        new (): HTMLNoiBackdropElement;
    };
    interface HTMLNoiButtonElementEventMap {
        "btnClick": MouseEvent;
    }
    /**
     * (INTERNAL) Backdrop component.
     */
    interface HTMLNoiButtonElement extends Components.NoiButton, HTMLStencilElement {
        addEventListener<K extends keyof HTMLNoiButtonElementEventMap>(type: K, listener: (this: HTMLNoiButtonElement, ev: NoiButtonCustomEvent<HTMLNoiButtonElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLNoiButtonElementEventMap>(type: K, listener: (this: HTMLNoiButtonElement, ev: NoiButtonCustomEvent<HTMLNoiButtonElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLNoiButtonElement: {
        prototype: HTMLNoiButtonElement;
        new (): HTMLNoiButtonElement;
    };
    /**
     * (INTERNAL) render an icon.
     * Icons are embedded inside the component (so far).
     * Icon size can be changed by 'font-size' style
     */
    interface HTMLNoiIconElement extends Components.NoiIcon, HTMLStencilElement {
    }
    var HTMLNoiIconElement: {
        prototype: HTMLNoiIconElement;
        new (): HTMLNoiIconElement;
    };
    interface HTMLNoiInputElementEventMap {
        "valueChange": string;
    }
    /**
     * (INTERNAL) render an input with prefix and clear button
     * Prefix are hardcoded to 'search' icon for now.
     */
    interface HTMLNoiInputElement extends Components.NoiInput, HTMLStencilElement {
        addEventListener<K extends keyof HTMLNoiInputElementEventMap>(type: K, listener: (this: HTMLNoiInputElement, ev: NoiInputCustomEvent<HTMLNoiInputElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLNoiInputElementEventMap>(type: K, listener: (this: HTMLNoiInputElement, ev: NoiInputCustomEvent<HTMLNoiInputElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLNoiInputElement: {
        prototype: HTMLNoiInputElement;
        new (): HTMLNoiInputElement;
    };
    interface HTMLNoiMapElementEventMap {
        "mapReady": Map;
    }
    /**
     * (INTERNAL) render leaflet map
     */
    interface HTMLNoiMapElement extends Components.NoiMap, HTMLStencilElement {
        addEventListener<K extends keyof HTMLNoiMapElementEventMap>(type: K, listener: (this: HTMLNoiMapElement, ev: NoiMapCustomEvent<HTMLNoiMapElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLNoiMapElementEventMap>(type: K, listener: (this: HTMLNoiMapElement, ev: NoiMapCustomEvent<HTMLNoiMapElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLNoiMapElement: {
        prototype: HTMLNoiMapElement;
        new (): HTMLNoiMapElement;
    };
    interface HTMLElementTagNameMap {
        "noi-a22-air-quality": HTMLNoiA22AirQualityElement;
        "noi-air-quality-list": HTMLNoiAirQualityListElement;
        "noi-backdrop": HTMLNoiBackdropElement;
        "noi-button": HTMLNoiButtonElement;
        "noi-icon": HTMLNoiIconElement;
        "noi-input": HTMLNoiInputElement;
        "noi-map": HTMLNoiMapElement;
    }
}
declare namespace LocalJSX {
    /**
     * Road air quality component
     */
    interface NoiA22AirQuality {
        /**
          * Language
         */
        "language"?: string;
        /**
          * Layout appearance
         */
        "layout"?: ViewLayout;
    }
    /**
     * (INTERNAL) part of 'noi-a22-air-quality'
     */
    interface NoiAirQualityList {
        "idSelected"?: string;
        "layout"?: ViewLayout;
        "onItemClick"?: (event: NoiAirQualityListCustomEvent<AirQualityShort>) => void;
        "stationArr"?: AirQualityShort[] | null;
    }
    /**
     * (INTERNAL) Backdrop component.
     */
    interface NoiBackdrop {
        /**
          * Removing backdrop from DOM sometime can cause blink during layout recalculation. 'hidden' can be used to hide the backdrop without removing from DOM
          * @default false
         */
        "hidden"?: boolean;
        /**
          * Emitted when user clicks on the backdrop
         */
        "onBackdropClick"?: (event: NoiBackdropCustomEvent<void>) => void;
    }
    /**
     * (INTERNAL) Backdrop component.
     */
    interface NoiButton {
        /**
          * button 'disabled' property
          * @default false
         */
        "disabled"?: boolean;
        /**
          * icon-only buttons has circle shape. The size of the button can be changed with "font-size" style
          * @default false
         */
        "iconOnly"?: boolean;
        /**
          * Emitted when user clicks on the button
         */
        "onBtnClick"?: (event: NoiButtonCustomEvent<MouseEvent>) => void;
    }
    /**
     * (INTERNAL) render an icon.
     * Icons are embedded inside the component (so far).
     * Icon size can be changed by 'font-size' style
     */
    interface NoiIcon {
        /**
          * icon name
         */
        "name"?: IconName | string;
    }
    /**
     * (INTERNAL) render an input with prefix and clear button
     * Prefix are hardcoded to 'search' icon for now.
     */
    interface NoiInput {
        /**
          * Emitted when value is changed
         */
        "onValueChange"?: (event: NoiInputCustomEvent<string>) => void;
        /**
          * Input placeholder
         */
        "placeholder"?: string;
    }
    /**
     * (INTERNAL) render leaflet map
     */
    interface NoiMap {
        /**
          * Emitted when map is initialized and ready to draw on it
         */
        "onMapReady"?: (event: NoiMapCustomEvent<Map>) => void;
    }
    interface IntrinsicElements {
        "noi-a22-air-quality": NoiA22AirQuality;
        "noi-air-quality-list": NoiAirQualityList;
        "noi-backdrop": NoiBackdrop;
        "noi-button": NoiButton;
        "noi-icon": NoiIcon;
        "noi-input": NoiInput;
        "noi-map": NoiMap;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            /**
             * Road air quality component
             */
            "noi-a22-air-quality": LocalJSX.NoiA22AirQuality & JSXBase.HTMLAttributes<HTMLNoiA22AirQualityElement>;
            /**
             * (INTERNAL) part of 'noi-a22-air-quality'
             */
            "noi-air-quality-list": LocalJSX.NoiAirQualityList & JSXBase.HTMLAttributes<HTMLNoiAirQualityListElement>;
            /**
             * (INTERNAL) Backdrop component.
             */
            "noi-backdrop": LocalJSX.NoiBackdrop & JSXBase.HTMLAttributes<HTMLNoiBackdropElement>;
            /**
             * (INTERNAL) Backdrop component.
             */
            "noi-button": LocalJSX.NoiButton & JSXBase.HTMLAttributes<HTMLNoiButtonElement>;
            /**
             * (INTERNAL) render an icon.
             * Icons are embedded inside the component (so far).
             * Icon size can be changed by 'font-size' style
             */
            "noi-icon": LocalJSX.NoiIcon & JSXBase.HTMLAttributes<HTMLNoiIconElement>;
            /**
             * (INTERNAL) render an input with prefix and clear button
             * Prefix are hardcoded to 'search' icon for now.
             */
            "noi-input": LocalJSX.NoiInput & JSXBase.HTMLAttributes<HTMLNoiInputElement>;
            /**
             * (INTERNAL) render leaflet map
             */
            "noi-map": LocalJSX.NoiMap & JSXBase.HTMLAttributes<HTMLNoiMapElement>;
        }
    }
}
